### ISSUE TITLE
Error communicating with bot chatGPT

### ISSUE THREAD

**Issue by Drak0** [poe-platform/server-bot-quick-start#40]
followed the tutorial in here : https://developer.poe.com/api-bots/quick-start
i also enabled the POE_API_KEY, i send it in the request in the BEARER.

EchoBot and HuggingFaceBot works perfectly when making an api calling using postman.
however, when switching to ChatGPTAllCapsBot or the example in here https://developer.poe.com/api-bots/api-to-access-bots-on-poe i get the error below:

Sending request to chatGPT...
Request finished with status 200. (execution time: 6.9 ms, total latency: 1805.2 ms)
Error in Poe API Bot: Bot request to chatGPT failed on try 0 {"allow_retry": true, "text": "Internal server error"}
Error in Poe API Bot: Bot request to chatGPT failed on try 1 {"allow_retry": true, "text": "Internal server error"}
Error occurred: Error communicating with bot chatGPT
Error responding to query
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 321, in stream_request
    async for message in ctx.perform_query_request(request):
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1580, in stream
    yield response
  File "/usr/local/lib/python3.11/site-packages/httpx_sse/_api.py", line 70, in aconnect_sse
    yield EventSource(response)
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 225, in perform_query_request
    raise BotError(event.data)
fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/base.py", line 169, in handle_query
    async for event in self.get_response(query):
  File "/root/chatgpt_allcapsbot.py", line 33, in get_response
    raise e
  File "/root/chatgpt_allcapsbot.py", line 12, in get_response
    async for msg in stream_request(query, "chatGPT", query.api_key):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 330, in stream_request
    raise BotError(f"Error communicating with bot {bot_name}") from e
fastapi_poe.client.BotError: Error communicating with bot chatGPT
if i use the BOT i created by sending aprompt from the POE website, it works.

**Comment by acid23m** [comment]
I got a similar error.

Sample request from docs
```
{
    "version": "1.0",
    "type": "query",
    "query": [
        {
            "role": "user",
            "content": "What is the capital of Nepal?",
            "content_type": "text/markdown",
            "timestamp": 1678299819427621
        }
    ],
    "user_id": "u-1234abcd5678efgh",
    "conversation_id": "c-jklm9012nopq3456",
    "message_id": "m-abc123qqq111890g"
}
```

Error
```
Error in Poe API Bot: Bot request to chatGPT failed on try 1 {"allow_retry": true, "text": "Internal server error: length of decrypt input is not 17: jklm9012nopq3456"}
```

What does it mean?

--

P.S. 
Documentation says "identifier regex ^[a-z]{1,3}-[a-z0-9=]{32}$"

**Comment by NotF404** [comment]
Can someone make a step by step tourtorial, to make python acesses to poe

**Comment by TheLime1** [comment]
yes , without changing anything in this repo chatgpt dosnt work out-of the-box
erorr :
```
Error responding to query
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 320, in stream_request
    async for message in ctx.perform_query_request(request):
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1580, in stream
    yield response
  File "/usr/local/lib/python3.11/site-packages/httpx_sse/_api.py", line 70, in aconnect_sse
    yield EventSource(response)
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 213, in perform_query_request
    raise BotError(event.data)
fastapi_poe.client.BotError: {"allow_retry": true, "text": "Message m-000000xy92lps2w1bhfwh4qqpd1c5fh8 called on bot that is not defined in settings. Or the number of calls made to bot has exceeded defined count in settings."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/base.py", line 174, in handle_query
    async for event in self.get_response(query):
  File "/root/chatgpt_allcapsbot.py", line 15, in get_response
    async for msg in stream_request(query, "ChatGPT", query.access_key):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 329, in stream_request
    raise BotError(f"Error communicating with bot {bot_name}") from e
fastapi_poe.client.BotError: Error communicating with bot ChatGPT
```

**Comment by TheLime1** [comment]
even the other bots
![image](https://github.com/poe-platform/server-bot-quick-start/assets/47940043/fae32407-8dc1-4b9d-9de8-b43892206cca)

**Comment by kreamyu** [comment]
> You cannot just make up the identifiers; they _must_ come from an actual Poe request to your server.

Hello, I encountered the same problem and I found out: `GPT-3.5-Turbo` works but `Claude-instant` does not work. Do you know the reason?
Here is the error message:
```
Error in Poe bot: Bot request to Claude-instant failed on try 19 {"allow_retry": true, "text": "Message m-000000xy92m3be9m4f7673cm7fdwdlq3 called on bot that is not defined in settings. Or the number of calls made to bot has exceeded defined count in settings."}
Error responding to query
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fastapi_poe/client.py", line 320, in stream_request
    async for message in ctx.perform_query_request(request):
  File "/usr/local/lib/python3.8/site-packages/fastapi_poe/client.py", line 213, in perform_query_request
    raise BotError(event.data)
fastapi_poe.client.BotError: {"allow_retry": true, "text": "Message m-000000xy92m3be9m4f7673cm7fdwdlq3 called on bot that is not defined in settings. Or the number of calls made to bot has exceeded defined count in settings."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fastapi_poe/base.py", line 174, in handle_query
    async for event in self.get_response(query):
  File "/root/chatbot.py", line 24, in get_response
    async for msg in stream_request(request, "Claude-instant", request.access_key, num_tries=20):
  File "/usr/local/lib/python3.8/site-packages/fastapi_poe/client.py", line 329, in stream_request
    raise BotError(f"Error communicating with bot {bot_name}") from e
fastapi_poe.client.BotError: Error communicating with bot Claude-instant
```

**Comment by anmolsingh95** [comment]
Does this tutorial help? https://developer.poe.com/server-bots/accessing-other-bots-on-poe
