### ISSUE TITLE
Broken code to package modal

### ISSUE THREAD

**Issue by Dyl777** [poe-platform/server-bot-quick-start#61]
################################################################################
#             Something with the Modal installation seems broken.              #
#           Please email support@modal.com and we will try to help!            #
################################################################################
#on trying to output main.py
Traceback (most recent call last):
  File "/workspace/server-bot-quick-start/main.py", line 8, in <module>
    from modal import Image, Stub, asgi_app
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/modal/__init__.py", line 6, in <module>
    from .app import container_app, is_local
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/modal/app.py", line 17, in <module>
    from .object import _Object
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/modal/object.py", line 23, in <module>
    _BLOCKING_O = synchronize_api(O)
                  ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/modal_utils/async_utils.py", line 31, in synchronize_api
    return synchronizer.create_blocking(obj, blocking_name, target_module=target_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/synchronicity/synchronizer.py", line 687, in create_blocking
    wrapped = self._wrap(obj, Interface.BLOCKING, name, target_module=target_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/synchronicity/synchronizer.py", line 623, in _wrap
    if self._wrapped_attr not in obj.__dict__:
                                 ^^^^^^^^^^^^
AttributeError: 'typing.TypeVar' object has no attribute '__dict__'. Did you mean: '__dir__'?
gitpod /workspace/server-bot-quick-start (main) $

**Comment by anmolsingh95** [comment]
I just tried setting up the echobot by cloning this repo alongwith a fresh installation of the modal-client. Could you please share the exact steps you used to reproduce this issue?
